databases: 
  - name: portfolio_sql
    databaseName: portfolio_sql
    user: portfolio_sql_user

services:
  - type: web
    name: alumicarpin
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
        name: conc-settings
        property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
