databases: portfolio_sql
  - name: portffolio_db
    databaseName: portfolio_sql
    user: Tony

services:
  - type: web
    name: alumicarpin
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase: postgres://portfolio_sql_user:LbhKOmolNmPNxYKzfsNbC6tq5mBnrnmj@dpg-cj30m8t9aq0e0q5641eg-a/portfolio_sql
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
